// Convenience header that includes all effect class definitions.
// Include this in .cpp files that need to call methods on RKR's effect members.

#ifndef ALL_EFFECTS_HPP
#define ALL_EFFECTS_HPP

#include "FPreset.hpp"
#include "Reverb.hpp"
#include "Chorus.hpp"
#include "Echo.hpp"
#include "Phaser.hpp"
#include "APhaser.hpp"
#include "Distorsion.hpp"
#include "EQ.hpp"
#include "Compressor.hpp"
#include "DynamicFilter.hpp"
#include "Alienwah.hpp"
#include "Pan.hpp"
#include "Harmonizer.hpp"
#include "MusicDelay.hpp"
#include "Gate.hpp"
#include "NewDist.hpp"
#include "Tuner.hpp"
#include "RecognizeNote.hpp"
#include "RecChord.hpp"
#include "Valve.hpp"
#include "Dual_Flange.hpp"
#include "Ring.hpp"
#include "Exciter.hpp"
#include "MBDist.hpp"
#include "Arpie.hpp"
#include "Expander.hpp"
#include "Shuffle.hpp"
#include "Synthfilter.hpp"
#include "MBVvol.hpp"
#include "Convolotron.hpp"
#include "Resample.hpp"
#include "AnalogFilter.hpp"
#include "Looper.hpp"
#include "RyanWah.hpp"
#include "RBEcho.hpp"
#include "CoilCrafter.hpp"
#include "ShelfBoost.hpp"
#include "Vocoder.hpp"
#include "Sustainer.hpp"
#include "Sequence.hpp"
#include "Shifter.hpp"
#include "StompBox.hpp"
#include "Reverbtron.hpp"
#include "Echotron.hpp"
#include "StereoHarm.hpp"
#include "CompBand.hpp"
#include "Opticaltrem.hpp"
#include "Vibe.hpp"
#include "Infinity.hpp"
#include "beattracker.hpp"
#include "metronome.hpp"

#endif
