name: Build on macOS

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        if brew tap | grep -qx 'aws/tap'; then
          brew untap aws/tap
        fi
        brew install fftw jack libsamplerate libsndfile nlohmann-json pkg-config qt@6

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build